version: 2.1
orbs:
  android: circleci/android@0.2.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-ndk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - run:
          name: Git nonsense
          command: git config --global user.email "ci@beatscratch.io" && git config --global user.name "CI testing"

      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install autotools-dev automake autoconf libtool g++ autopoint make cmake
                   bison flex yasm pkg-config gtk-doc-tools libxv-dev libx11-dev libpulse-dev
                   python3-dev texinfo gettext build-essential pkg-config doxygen curl libxext-dev
                   libxi-dev x11proto-record-dev libxrender-dev libgl1-mesa-dev libxfixes-dev
                   libxdamage-dev libxcomposite-dev libasound2-dev libxml-simple-perl dpkg-dev
                   debhelper build-essential devscripts fakeroot transfig gperf libdbus-glib-1-dev
                   wget glib-networking libxtst-dev libxrandr-dev libglu1-mesa-dev libegl1-mesa-dev
                   git subversion xutils-dev intltool ccache python3-setuptools autogen maven
#      - install-ndk
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
#      - run:
#          name: Build JNAerator
#          working_directory: external/JNAerator
#          command: mvn package

      - run:
          name: Prepare fluidsynthjna
          working_directory: fluidsynthjna
          command: make prepare-fluidsynth
      - run:
          name: Build fluidsynthjna
          working_directory: fluidsynthjna
          command: make
      - store_artifacts:
          path: fluidsynthjna/src/main/jniLibs
          destination: jniLibs
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Build debug and release APKs
          command: ./gradlew assembleDebug assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
